[package]
name = "game"
version = "0.1.0"
authors = ["Garrett Steffen <garrettsteffen@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.47"
js-sys = "0.3.24"
web-sys = "0.3.24"
console_error_panic_hook = "0.1.6"
specs = "0.15.0"

[dependencies.goblin]
path = "../../engine"
